/**
 * Static Handler Manifest
 * 
 * This file is AUTO-GENERATED by scripts/generate-manifest.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 * 
 * To regenerate this file, run: bun run generate-manifest
 * 
 * This manifest explicitly imports and exports all interaction handlers for Cloudflare Workers.
 * Unlike the dynamic loader that uses Bun.Glob (which doesn't work in Workers), this manifest
 * statically imports all handlers at build time, ensuring they're bundled into the Worker.
 * 
 * @module manifest
 * @generated
 */

// Command imports (5)
import demo from '../../commands/demo';
import example from '../../commands/example';
import greet from '../../commands/greet';
import manage from '../../commands/manage';
import ping from '../../commands/ping';

// Button imports (6)
import cancel from '../../buttons/cancel';
import confirm from '../../buttons/confirm';
import deleteButton from '../../buttons/delete';
import openFeedbackModal from '../../buttons/open_feedback_modal';
import testButton from '../../buttons/test_button';
import testModalOpen from '../../buttons/test_modal_open';

// Modal imports (3)
import feedback from '../../modals/feedback';
import report from '../../modals/report';
import testModal from '../../modals/test_modal';

// Select menu imports (4)
import channelSelect from '../../select-menus/channel_select';
import menuSelect from '../../select-menus/menu_select';
import roleSelect from '../../select-menus/role_select';
import testSelect from '../../select-menus/test_select';

import type { Command, Button, Modal, Select } from './loader';

/**
 * Array of all command handlers.
 */
export const commands: Command[] = [
  demo,
  example,
  greet,
  manage,
  ping,
];

/**
 * Array of all button handlers.
 */
export const buttons: Button[] = [
  cancel,
  confirm,
  deleteButton,
  openFeedbackModal,
  testButton,
  testModalOpen,
];

/**
 * Array of all modal handlers.
 */
export const modals: Modal[] = [
  feedback,
  report,
  testModal,
];

/**
 * Array of all select menu handlers.
 */
export const selects: Select[] = [
  channelSelect,
  menuSelect,
  roleSelect,
  testSelect,
];
